language: node_js

node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
    - open-zwave-master

sudo: required

env:
  global:
    - CC=gcc-4.9
    - CXX=g++-4.9
    - MOZIOT_HOME=/home/travis/.mozilla-iot/test
    - NODE_TLS_REJECT_UNAUTHORIZED=0

addons:
  firefox: "62.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libudev-dev

before_install:
  - pyenv global system 3.6

install:
  - git clone https://github.com/mozilla-iot/intent-parser
  - pip3.6 install --user -e git+https://github.com/mycroftai/adapt#egg=adapt-parser
  - python3.6 intent-parser/intent-parser-server.py &
  - ./tools/compile-openzwave.sh

before_script:
  - pyenv global system 2.7

script:
  - yarn
  - node ./node_modules/webpack/bin/webpack.js
  - yarn run lint
  - ./tools/make-self-signed-cert.sh
  - ./node_modules/.bin/jest --runInBand --coverage
  - yarn run yarn-check
  - yarn run dependencies-check

after_script:
  - ./node_modules/.bin/codecov
