version: "3"

services:
  webthings-gateway:
    container_name: webthings-gateway
    build: .
    restart: unless-stopped
    network_mode: host
    # "ports" are ignored because of "network_mode: host". Either use "ports"
    # or "network_mode: host".
    #ports:
    #  - "8080:8080"
    #  - "4443:4443"
    environment:
      - "TZ=America/Los_Angeles"
      - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
    volumes:
      - /opt/docker/webthings-gateway:/home/node/.webthings
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    labels:
      io.balena.features.dbus: '1'
    # If certain devices are needed, e.g. USB dongles, enable them here.
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/ttyACM0:/dev/ttyACM0
    # If Bluetooth, the container needs to run in privileged mode.
    #privileged: true
