basepath = "."

locales = [
  "de",
  "fr-CA",
  "fr-FR",
  "fy-NL",
  "it",
  "nl",
  "pl",
  "ru"
]

branches = [
  "master",
]

[[paths]]
  reference = "static/fluent/en-US/main.ftl"
  l10n = "static/fluent/{locale}/main.ftl"
