basepath = "."

locales = [
  "cs",
  "cy",
  "de",
  "en-CA",
  "en-GB",
  "es-AR",
  "es-ES",
  "fr",
  "fy-NL",
  "hu",
  "ia",
  "id",
  "it",
  "ja",
  "kab",
  "nl",
  "pl",
  "pt-BR",
  "ru",
  "sk",
  "sr",
  "sv-SE",
  "ta",
  "zh-CN",
  "zh-TW",
]

branches = [
  "master",
]

[[paths]]
  reference = "static/fluent/en-US/main.ftl"
  l10n = "static/fluent/{locale}/main.ftl"
